-- =========================================================
-- RFM ANALYSIS PROJECT
-- Purpose:
-- Build a complete customer-level RFM (Recency, Frequency,
-- Monetary) segmentation model using SQL.

-- Workflow:
-- 1. Aggregate transactional data at customer level
-- 2. Calculate customer recency
-- 3. Generate percentile-based RFM scores using NTILE
-- 4. Create customer segments for business analysis
-- =========================================================



-- =========================================================
-- STEP 1: CREATE CUSTOMER-LEVEL RFM BASE TABLE
-- =========================================================
-- This table aggregates raw transactional data into
-- one row per customer.
--
-- Metrics created:
-- Frequency  = Number of unique orders
-- Monetary   = Total customer spending (Net Revenue)
-- Last Purchase Date = Most recent customer order date
-- =========================================================

CREATE TABLE rfm_base AS
SELECT
    c.customer_unique_id,
    -- Frequency: Counts how many unique orders each customer made
    COUNT(DISTINCT o.order_id) AS frequency,
    -- Monetary: Total revenue generated by each customer
    -- Rounded to 2 decimal places
    ROUND(SUM(oi.price), 2) AS monetary,
    -- Last Purchase Date: Most recent purchase timestamp for each customer
    MAX(o.order_purchase_timestamp) AS customer_last_purchase_date
FROM orders AS o
INNER JOIN order_items AS oi ON o.order_id = oi.order_id
INNER JOIN customers AS c ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id;



-- =========================================================
-- STEP 2: CREATE RECENCY TABLE
-- =========================================================
-- Recency measures how recently a customer purchased.
-- Logic: Recency = Difference between: Latest purchase date in entire dataset and customer's last purchase date
-- Lower recency value = more recent customer
-- =========================================================

CREATE TABLE rfm_recency AS
SELECT
    -- Select all columns from rfm_base
    r.*,
    DATEDIFF(
        -- Global maximum purchase date in dataset
        (SELECT MAX(customer_last_purchase_date)
         FROM rfm_base),
        -- Customer's most recent purchase date
        r.customer_last_purchase_date
    ) AS recency
FROM rfm_base r;


-- =========================================================
-- STEP 3: CREATE RFM SCORES TABLE
-- =========================================================
-- This step converts raw RFM metrics into percentile- based scores using NTILE(5).
-- Score Range:
-- 1 = Lowest customer value
-- 5 = Highest customer value
-- NTILE(5):
-- Splits customers into 5 equal-sized groups.
-- =========================================================
CREATE TABLE rfm_scores AS
SELECT *,
    -- NTILE normally assigns:
    -- smallest value = 1
    -- largest value  = 5

    -- But I reverse the recency score using:
    -- 6 - NTILE(...)
    -- Final Logic for recency:
    -- Most recent customers  = 5
    -- Least recent customers = 1
    -- =====================================================
    6 - NTILE(5) OVER (ORDER BY recency ASC) AS r_score,
    NTILE(5) OVER (ORDER BY frequency ASC) AS f_score,
    NTILE(5) OVER (ORDER BY monetary ASC) AS m_score
FROM rfm_recency;



-- =========================================================
-- STEP 4: CREATE FINAL RFM TABLE
-- =========================================================
-- This is the final customer segmentation table.
-- Additional fields:
-- RFM Score  = Combined RFM code
-- Segment    = Business-defined customer category
-- =========================================================
CREATE TABLE rfm_table AS
SELECT 
    customer_unique_id,
    recency,
    frequency,
    monetary,
    
    -- RFM scores
    r_score,
    f_score,
    m_score,

    -- Combined RFM score
    -- Example:
    -- 555 = Best customers
    -- 111 = Lowest-value customers
    CONCAT(r_score, f_score, m_score) AS rfm_score,

    -- =====================================================
    -- CUSTOMER SEGMENTATION LOGIC
    -- =====================================================
    -- Customers are grouped into business segments
    -- based on RFM behavior patterns.
    -- =====================================================
    CASE
        -- High-value and highly engaged customers
        WHEN r_score >= 4 AND f_score >= 4
        THEN 'Champions'
        -- Frequent repeat customers
        WHEN f_score >= 3
        THEN 'Loyal Customers'
        -- Recently acquired customers
        WHEN r_score >= 4 AND f_score <= 2
        THEN 'Recent New Customers'
        -- Previously active but becoming inactive
        WHEN r_score <= 2 AND f_score >= 3
        THEN 'At Risk'
        -- Highly inactive customers
        WHEN r_score <= 1
        THEN 'Lost'
        -- Average or developing customers
        ELSE 'Potential/Standard'
    END AS segment
FROM rfm_scores;